# Generated by Django 5.1.3 on 2024-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='phoneNumber',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
